const fileEl=document.getElementById('file'),drop=document.getElementById('drop'),preview=document.getElementById('preview'),nameEl=document.getElementById('name');
const framesEl=document.getElementById('frames'),fpsEl=document.getElementById('fps'),pixelEl=document.getElementById('pixel'),motionEl=document.getElementById('motion');
const framesOut=document.getElementById('framesOut'),fpsOut=document.getElementById('fpsOut'),pixelOut=document.getElementById('pixelOut'),motionOut=document.getElementById('motionOut');
const generate=document.getElementById('generate'),pngButton=document.getElementById('png'),statusEl=document.getElementById('status'),output=document.getElementById('output'),sizeEl=document.getElementById('size');
let source=null,lastPng=null,lastGif=null;
const target=new Image(); target.src='assets/target.png';
function sync(){framesOut.textContent=framesEl.value;fpsOut.textContent=fpsEl.value;pixelOut.textContent=pixelEl.value;motionOut.textContent=motionEl.value+'%'}
[framesEl,fpsEl,pixelEl,motionEl].forEach(x=>x.addEventListener('input',sync));sync();
fileEl.addEventListener('change',e=>{if(e.target.files[0])load(e.target.files[0])});
['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.style.borderColor='#f4c542'}));
['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.style.borderColor=''}));
drop.addEventListener('drop',e=>{if(e.dataTransfer.files[0])load(e.dataTransfer.files[0])});
function load(file){if(!file.type.startsWith('image/'))return statusEl.textContent='Please select an image.';nameEl.textContent=file.name;const r=new FileReader();r.onload=()=>{source=new Image();source.onload=()=>{preview.src=r.result;preview.classList.remove('hidden');drop.classList.add('hidden');generate.disabled=false;statusEl.textContent='Ready to transform.'};source.src=r.result};r.readAsDataURL(file)}
function fit(w,h,max=640){const s=Math.min(1,max/Math.max(w,h));return [Math.max(2,Math.round(w*s)),Math.max(2,Math.round(h*s))]}
function rgb(data,i){return[data[i],data[i+1],data[i+2],data[i+3]]}
function mix(a,b,t){return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t]}
function buildMaps(w,h,pixel){const countX=Math.floor(w/pixel),countY=Math.floor(h/pixel),n=countX*countY;const src=[],dst=[];for(let y=0;y<countY;y++)for(let x=0;x<countX;x++){src.push([x*pixel+pixel/2,y*pixel+pixel/2]);dst.push([x*pixel+pixel/2,y*pixel+pixel/2])}const seed=17;let s=seed;for(let i=dst.length-1;i>0;i--){s=(s*1664525+1013904223)>>>0;const j=s%(i+1);[dst[i],dst[j]]=[dst[j],dst[i]]}return{src,dst,n}}
function drawFrame(ctx,w,h,t,pixel,maps,srcData,targetData,motion){ctx.clearRect(0,0,w,h);ctx.fillStyle='#08090b';ctx.fillRect(0,0,w,h);const a=Math.min(1,Math.max(0,t));const ease=a*a*(3-2*a);const amp=(1-ease)*motion*.01;for(let i=0;i<maps.n;i++){const sp=maps.src[i],dp=maps.dst[i];const x=sp[0]+(dp[0]-sp[0])*ease+Math.sin(i*12.73)*amp*w*.035*(1-ease);const y=sp[1]+(dp[1]-sp[1])*ease+Math.cos(i*8.17)*amp*h*.035*(1-ease);const sx=Math.min(w-1,Math.max(0,Math.floor(sp[0]))),sy=Math.min(h-1,Math.max(0,Math.floor(sp[1])));const di=(sy*w+sx)*4;const tx=Math.min(w-1,Math.max(0,Math.floor(dp[0]))),ty=Math.min(h-1,Math.max(0,Math.floor(dp[1])));const ti=(ty*w+tx)*4;const c=mix(rgb(srcData,di),rgb(targetData,ti),ease);ctx.fillStyle=`rgb(${c[0]|0},${c[1]|0},${c[2]|0})`;ctx.fillRect(Math.round(x-pixel/2),Math.round(y-pixel/2),pixel,pixel)}}
async function render(){if(!source)return;generate.disabled=true;pngButton.disabled=true;statusEl.textContent='Preparing pixels...';output.innerHTML='<span>Rendering transformation...</span>';sizeEl.textContent='';if(!target.complete)await new Promise(r=>target.onload=r);const [w,h]=fit(source.width,source.height);const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,0,0,w,h);const srcData=ctx.getImageData(0,0,w,h).data;ctx.clearRect(0,0,w,h);ctx.drawImage(target,0,0,w,h);const targetData=ctx.getImageData(0,0,w,h).data;const maps=buildMaps(w,h,+pixelEl.value);const frames=+framesEl.value;const delay=Math.round(1000/+fpsEl.value);const gif=new GIF({workers:2,quality:1,width:w,height:h,workerScript:'https://cdn.jsdelivr.net/npm/gif.js@0.2.0/dist/gif.worker.js'});for(let i=0;i<frames;i++){const t=i/(frames-1);drawFrame(ctx,w,h,t,+pixelEl.value,maps,srcData,targetData,+motionEl.value);gif.addFrame(ctx,{copy:true,delay});statusEl.textContent=`Rendering frame ${i+1} of ${frames}...`;await new Promise(r=>requestAnimationFrame(r))}gif.on('progress',p=>statusEl.textContent=`Encoding GIF ${Math.round(p*100)}%...`);gif.on('finished',blob=>{if(lastGif)URL.revokeObjectURL(lastGif);lastGif=URL.createObjectURL(blob);output.innerHTML='';const im=document.createElement('img');im.src=lastGif;im.alt='Trumpify transformation GIF';output.appendChild(im);sizeEl.textContent=format(blob.size);const final=document.createElement('canvas');final.width=w;final.height=h;const f=final.getContext('2d');drawFrame(f,w,h,1,+pixelEl.value,maps,srcData,targetData,+motionEl.value);final.toBlob(b=>{lastPng=b;pngButton.disabled=false},'image/png');generate.disabled=false;statusEl.textContent='Done. The GIF shows the pixels moving into the Trump portrait.'});gif.render()}
generate.addEventListener('click',render);pngButton.addEventListener('click',()=>{if(!lastPng)return;const a=document.createElement('a');a.href=URL.createObjectURL(lastPng);a.download='trumpify.png';a.click()});function format(n){return n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB'}
